export const ADD_TRACKER = "ADD_TRACKER"
export const ADD_TRACKERS = "ADD_TRACKERS"
export const INCREMENT_TRACKER = "INCREMENT_TRACKER"
export const ADD_INCREMENT = "ADD_INCREMENT"
export const ADD_INCREMENTS = "ADD_INCREMENTS"

