export const ADD_TRACKER = "ADD_TRACKER"
export const ADD_TRACKERS = "ADD_TRACKERS"
export const ADD_INCREMENT = "ADD_INCREMENT"
export const ADD_INCREMENTS = "ADD_INCREMENTS"
export const INCREMENT_TRACKER = "INCREMENT_TRACKER"
export const UPDATE_SETTING = "UPDATE_SETTING"
export const UPDATE_NUM_INCREMENTS = "UPDATE_NUM_INCREMENTS"
export const UPDATE_TRACKER = "UPDATE_TRACKER"
export const DELETE_INCREMENT = "DELETE_INCREMENT"
export const DELETE_TRACKER = "DELETE_TRACKER"
export const DELETE_CLICK = "DELETE_CLICK"


