export const ADD_TRACKER = "ADD_TRACKER"
export const ADD_TRACKERS = "ADD_TRACKERS"
export const DELETE_TRACKER = "DELETE_TRACKER"
export const INCREMENT_TRACKER = "INCREMENT_TRACKER"
export const ADD_INCREMENT = "ADD_INCREMENT"
export const ADD_INCREMENTS = "ADD_INCREMENTS"
export const DELETE_INCREMENT = "DELETE_INCREMENT"

